### ISSUE TITLE
Plugin doesn't load after updating

### ISSUE THREAD

**Issue by KySoto** [maikebing/GitLab.VisualStudio#104]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.200

### Description
When i launch visual studio after updating the plugin i get this error
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitLab.VisualStudio.Services.Storage". ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at GitLab.VisualStudio.Services.Storage.LoadConfig()
   at GitLab.VisualStudio.Services.Storage..ctor()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

### Steps to recreate
1. start visual studio
2. see this error message.

### Current behavior
it wont load

### Expected behavior
it loads

**Comment by KySoto** [comment]
I also tried reinstalling the plugin just in case i was doing the dumb, im still getting the error

**Comment by maikebing** [comment]
[GitLab.VisualStudio.zip](https://github.com/maikebing/GitLab.VisualStudio/files/4865505/GitLab.VisualStudio.zip)

**Comment by KySoto** [comment]
I ran your new package, and i got
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitLab.VisualStudio.Services.Storage". ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at GitLab.VisualStudio.Services.Storage.LoadConfig()
   at GitLab.VisualStudio.Services.Storage..ctor()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by maikebing** [comment]
Can you help with the debugging?

**Comment by KySoto** [comment]
If you tell me how i can, sure, at my work our primary git solution is git lab, so i really really need this working.

**Comment by maikebing** [comment]
https://stackoverflow.com/questions/9281662/how-to-debug-visual-studio-extensions 
https://docs.microsoft.com/en-us/visualstudio/extensibility/starting-to-develop-visual-studio-extensions?view=vs-2019

**Comment by KySoto** [comment]
So after looking at the SO question, i dont have the devenv executable.

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/86390691-1f6f6b00-bccb-11ea-8011-a6624abd8303.png)

**Comment by KySoto** [comment]
i feel dumb, i was looking in the wrong visual studio folder, i was in C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE 
That said, i have a huge number of build issues.

![image](https://user-images.githubusercontent.com/835408/86391735-1fca2080-bc4f-11ea-84d8-e8c92eaaf10b.png)

**Comment by maikebing** [comment]
vs2019 need .net 4.7.2 ， os , you can unload or remove  GitLab.TeamFoundation.16 , try again !

**Comment by KySoto** [comment]
![image](https://user-images.githubusercontent.com/835408/86392433-518fb700-bc50-11ea-8556-3c517fb75b1f.png)

**Comment by phamdtai** [comment]
I have the same error KySoto after installing 1.0.200.

**Comment by CacheChui** [comment]
Could anyone share the 1.0.189 package download link?
Many thanks.

**Comment by phamdtai** [comment]
> Could anyone share the 1.0.189 package download link?
> Many thanks.

I only have in my local. I can send you by email.

**Comment by CacheChui** [comment]
> > Could anyone share the 1.0.189 package download link?
> > Many thanks.
> 
> I only have in my local. I can send you by email.

please send to cache.chui@achiever.hk, thanks phamdtai

**Comment by luckygg** [comment]
I can see this error message also. This gitlab package doesn't work in my computer.

**Comment by AF340** [comment]
same issue than KySoto on vs2017 after updating

**Comment by jeffoulet** [comment]
Hi, same issue here as well, plugin won't load with vs2017

**Comment by iambluebird** [comment]
临时应急办法：
1. 在“工具 > 扩展和更新”里，更改扩展和更新设置，关闭掉“自动检查更新”，避免恢复后又出问题
2. 安装好最新的 1.0.200 版本，此时无法启动，会报错
3. 关掉vs，进入目录C:\Users\用户名\AppData\Local\Microsoft\VisualStudio\15.0_359f03b1\Extensions\ax0kcljw.jse，最后一层目录是个随机字符串，很容易找到，里面有 GitLab.VisualStudio.dll 这些文件，把整个目录压缩备份一个，然后删掉里面的文件
4. 找一个还没升级的开发环境下这个目录下的文件，1.0.189版本的，把下面所有文件复制进来

这样就可以正常启动插件了。。。。

**Comment by KySoto** [comment]
Could you sent it to  kysoto2@gmail.com?

> > Could anyone share the 1.0.189 package download link?
> > Many thanks.
> 
> I only have in my local. I can send you by email.

**Comment by KySoto** [comment]
Apparently on https://www.vsixgallery.com/extension/54803a44-49e0-4935-bba4-7d7d91682273/
its up to version 1.0.276 , this version works perfectly. (Note: this is the link on the the readme.md for Open Visx gallery)
