### ISSUE TITLE
Dependancy error

### ISSUE THREAD

**Issue by bassguy0050** [maikebing/GitLab.VisualStudio#105]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.200

### Description
Unable to access any repos from GitLab. Throws the below error:
Microsoft.VisualStudio.Composition.CompositionFailedException: Import "GitLab.TeamFoundation.TeamExplorerServices._storage" could not be satisfied. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitLab.VisualStudio.Services.Storage". ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at GitLab.VisualStudio.Services.Storage.LoadConfig()
   at GitLab.VisualStudio.Services.Storage..ctor()

### Steps to recreate
1. Update extension to current version
2. Close VS
3. Open VS
2. Navigate to Team Explorer in Visual Studio

### Current behavior
It does not show any details from GitLab in the Team Explorer tab, only the above error

### Expected behavior
I should see my GitLab details

**Comment by CacheChui** [comment]
You may refer this previous issue and try the latest version. 
[#104 ](https://github.com/maikebing/GitLab.VisualStudio/issues/104)

**Comment by bassguy0050** [comment]
It looks like that resolved the issue. Is there any reason why the version in the Extensions and Updates window in VS is different from the latest version?
