### ISSUE TITLE
Won't load in VS 2017

### ISSUE THREAD

**Issue by jeffoulet** [maikebing/GitLab.VisualStudio#160]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 1.0.319

### Current behavior
Failed to load plugin at VS start:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel.LoadRepositoriesAsync()
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel..ctor(IMessenger messenger, IShellService shell, IStorage storage, ITeamExplorerServices teamexplorer, IViewFactory viewFactory, IWebService web)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.InitializeView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by whocare87** [comment]
Hi,

Checked on the source code. the reference of Microsoft.VisualStudio.Threading is higher then the installed version of VS2017. 
able to rebuild the package with the correct dll?

**Comment by roeynissim** [comment]
same issue with VS2019

**Comment by nellonet** [comment]
I have same error about jeffoulet (in vs2017). I have installed all the last version but I have not resolved. Does everyone have a solution?
thanks

**Comment by sirboozebum** [comment]
I also get the same error message.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel.LoadRepositoriesAsync()
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel..ctor(IMessenger messenger, IShellService shell, IStorage storage, ITeamExplorerServices teamexplorer, IViewFactory viewFactory, IWebService web)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.InitializeView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by marcoguevara** [comment]
I got this error on VS Professional 2017 Version 15.9.28

**Comment by chriserikbarnes** [comment]
Here is how I fixed it.

1. go to nugget https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/16.5.132
2. download package. change extension to .zip and unpack it
3. find your extensions folder e.g. [user]/AppData/Local/Microsoft/VisualStudio/[random value]/Extensions/[random value that contains GitLab Extension] note: you will see GitLab dll files so you know you are in the right place
4. copy the Microsoft.VisualStudio.Threading.dll into your GitLab extension folder (above)
5. restart VisualStudio and the error should be gone

**Comment by idea-zone** [comment]
> Here is how I fixed it.
> 
> 1. go to nugget https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/16.5.132
> 2. download package. change extension to .zip and unpack it
> 3. find your extensions folder e.g. [user]/AppData/Local/Microsoft/VisualStudio/[random value]/Extensions/[random value that contains GitLab Extension] note: you will see GitLab dll files so you know you are in the right place
> 4. copy the Microsoft.VisualStudio.Threading.dll into your GitLab extension folder (above)
> 5. restart VisualStudio and the error should be gone

But It's will get a new issue:
System.MissingMethodException: 找不到方法:“Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()”。
   在 GitLab.TeamFoundation.Sync.GitLabPublishSection.Initialize(Object sender, SectionInitializeEventArgs e)
   在 Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by Palmutip** [comment]
> Here is how I fixed it.
> 
> 1. go to nugget https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/16.5.132
> 2. download package. change extension to .zip and unpack it
> 3. find your extensions folder e.g. [user]/AppData/Local/Microsoft/VisualStudio/[random value]/Extensions/[random value that contains GitLab Extension] note: you will see GitLab dll files so you know you are in the right place
> 4. copy the Microsoft.VisualStudio.Threading.dll into your GitLab extension folder (above)
> 5. restart VisualStudio and the error should be gone

Aqui deu certo amigo.
Muito obrigado

**Comment by rogerwperkins** [comment]
I was able to connect and clone my GitLab repository using the GitHub extension.
