### ISSUE TITLE
File not found error for Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by KySoto** [maikebing/GitLab.VisualStudio#185]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.333 
- 
### Description
when I launch visual studio I get the following error in the team explorer
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Threading, Version=16.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel.LoadRepositoriesAsync()
   at GitLab.TeamFoundation.ViewModels.ConnectSectionViewModel..ctor(IMessenger messenger, IShellService shell, IStorage storage, ITeamExplorerServices teamexplorer, IViewFactory viewFactory, IWebService web)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.InitializeView(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at GitLab.TeamFoundation.Connect.GitLabConnectSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
```

### Steps to recreate
1. Start visual studio
2. get error message box saying it failed to open the plugin correctly
3. open team explorer
4. see this error message

### Current behavior
its giving this error message

### Expected behavior
it loads properly

**Comment by AltairWorke** [comment]
I get this same error.  Everything I can read indicates that this was introduced AFTER version 1.0.189

Anybody aware on how to get a VISX build for this older version?
