### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by desperadomar** [maikebing/GitLab.VisualStudio#20]
This i what I am getting when logging
![2017-12-10_150142](https://user-images.githubusercontent.com/12626321/33804304-925ab3f0-ddbb-11e7-9a63-407990dfa143.png)
![2017-12-10_150224](https://user-images.githubusercontent.com/12626321/33804308-9e297bee-ddbb-11e7-9ed8-dec93a371fc7.png)

**Comment by maikebing** [comment]
Wath gitlab version ?

**Comment by maikebing** [comment]
can you select GitLab API V3?

**Comment by desperadomar** [comment]
the extention version is 1.0.0.118

**Comment by desperadomar** [comment]
one more thing i found is 
![2017-12-10_185520](https://user-images.githubusercontent.com/12626321/33806073-cd76fef6-dddb-11e7-9ba1-13ea66f233e9.png)

why bitbucket.org

**Comment by maikebing** [comment]
gitlab server version ?

**Comment by desperadomar** [comment]
i am trying to push it into my online account

**Comment by gitupdater** [comment]
```
{System.NullReferenceException: A reference to an object is not on an instance of an object.
   at NGitLab.Impl.HttpRequestor.Stream(String tailApiUrl, Action`1 parser)
   at NGitLab.Impl.HttpRequestor.To[T](String tailApiUrl)
   at NGitLab.GitLabClient.Connect(String hostUrl, String username, String password, ApiVersion apiVersion)
   at GitLab.VisualStudio.Services.WebService.LoginAsync(Boolean enable2fa, String host, String email, String password, ApiVersion apiVersion)
   at GitLab.VisualStudio.UI.ViewModels.LoginViewModel.<>c__DisplayClass49_0.<OnLogin>b__0()}
```

**Comment by gitupdater** [comment]
```
+$exception	{System.Exception: The remote server returned an error (NotFound): 
   at NGitLab.Impl.HttpRequestor.Stream(String tailApiUrl, Action`1 parser)
   at NGitLab.Impl.HttpRequestor.To[T](String tailApiUrl)
   at NGitLab.GitLabClient.Connect(String hostUrl, String username, String password, ApiVersion apiVersion)
   at GitLab.VisualStudio.Services.WebService.LoginAsync(Boolean enable2fa, String host, String email, String password, ApiVersion apiVersion)
   at GitLab.VisualStudio.UI.ViewModels.LoginViewModel.<>c__DisplayClass49_0.<OnLogin>b__0()}	System.Exception

```

**Comment by maikebing** [comment]
Now  update login mode is OAuth2, which can't be logon before because the new version of GitLab's API session has been discarded.

The two API login methods are supported in the login interface, and the old version of GitLab needs to be selected manually. The default is that the login mode is OAuth2 And API V4!

**Comment by desperadomar** [comment]
Nope still not solved, just tried now , it's not signing in

**Comment by maikebing** [comment]
Update to new version ! 1.0.0.119

**Comment by desperadomar** [comment]
Did that too

**Comment by desperadomar** [comment]
![2017-12-15_125518](https://user-images.githubusercontent.com/12626321/34034290-44f9b162-e197-11e7-8fc7-d34af579dff4.png)

**Comment by maikebing** [comment]
GitLab ApiV4 Oauth2   ?

**Comment by desperadomar** [comment]
![2017-12-15_125651](https://user-images.githubusercontent.com/12626321/34034345-7f5a0208-e197-11e7-9e5d-dda6db85c613.png)

**Comment by maikebing** [comment]
[GitLab.VisualStudio.zip](https://github.com/maikebing/GitLab.VisualStudio/files/1562218/GitLab.VisualStudio.zip)

**Comment by desperadomar** [comment]
yup that worked

**Comment by maikebing** [comment]
Fix HttpUtility.UrlEncode processing username or email causing problems that cannot be logged in
