### ISSUE TITLE
VS 2015  1.0.142 ver update error "Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: Visual Studio MPF 15.0"

### ISSUE THREAD

**Issue by eshkard** [maikebing/GitLab.VisualStudio#30]
Hi @maikebing ,
on update to version 1.0.142 got  error message:
Beginning to install extension to Microsoft Visual Studio Professional 2015...
Upgrading 'GitLab Extension for Visual Studio', version 1.0.0.122 to version 1.0.142.
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Visual Studio MPF 15.0
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)

Looks it is simmilar to : https://github.com/rionmonster/Glyphfriend/issues/87

Thank you

**Comment by eshkard** [comment]
[VSIXInstaller_dc5383eb-b899-45e0-b024-a50144d628d8.log](https://github.com/maikebing/GitLab.VisualStudio/files/2289650/VSIXInstaller_dc5383eb-b899-45e0-b024-a50144d628d8.log)
